# Service name for discovery
spring.application.name=customer-service

# Unique port for this microservice
server.port=8081

# Oracle Database connection (can be same DB, different schema if needed)
spring.datasource.url=jdbc:oracle:thin:@10.11.201.120:1522/XEPDB1
spring.datasource.username=customer_user
spring.datasource.password=customer_pass
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver



# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect



