spring.application.name=RetailApplication
spring.datasource.url=jdbc:oracle:thin:@10.11.200.12:1523/eblocasdb
spring.datasource.username=ocasmn
spring.datasource.password=ocasmn
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

