-- Create customer user/schema
BEGIN
   EXECUTE IMMEDIATE 'CREATE USER customer_user IDENTIFIED BY customer_pass';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01920 THEN NULL; ELSE RAISE; END IF; -- User exists
END;
/

-- Grant privileges
BEGIN
   EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO customer_user';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -01921 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Create CustomerProfile table
BEGIN
   EXECUTE IMMEDIATE '
   CREATE TABLE customer_user.CustomerProfile (
      customer_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      first_name           VARCHAR2(50) NOT NULL,
      last_name            VARCHAR2(50) NOT NULL,
      date_of_birth        DATE NOT NULL,
      gender               CHAR(1),
      email                VARCHAR2(100) UNIQUE NOT NULL,
      phone_number         VARCHAR2(20) UNIQUE NOT NULL,
      address_line1        VARCHAR2(100) NOT NULL,
      address_line2        VARCHAR2(100),
      city                 VARCHAR2(50) NOT NULL,
      state                VARCHAR2(50),
      postal_code          VARCHAR2(20),
      country              VARCHAR2(50) NOT NULL,
      account_type         VARCHAR2(20) NOT NULL,
      account_status       VARCHAR2(20) DEFAULT ''Active'',
      registration_date    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      last_update_date     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      preferred_language   VARCHAR2(10),
      loyalty_program_status VARCHAR2(20),
      kyc_verified         CHAR(1) DEFAULT ''N'' CHECK (kyc_verified IN (''Y'', ''N'')),
      notes                CLOB
   )';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -955 THEN NULL; ELSE RAISE; END IF; -- Table exists
END;
/

-- Create trigger for auto-updating last_update_date
BEGIN
   EXECUTE IMMEDIATE '
   CREATE OR REPLACE TRIGGER customer_user.trg_customer_update
   BEFORE UPDATE ON customer_user.CustomerProfile
   FOR EACH ROW
   BEGIN
      :NEW.last_update_date := SYSTIMESTAMP;
   END;';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -4080 THEN NULL; ELSE RAISE; END IF; -- Trigger exists
END;
/
