#import properties files
spring.config.import=optional:file:./config.properties
#all value is defined in app.name in config file
#application properties
spring.application.name=${app.name} 
#server properties
server.port=${app.port}
#Database Credentials
spring.datasource.url=${app.url}
spring.datasource.username=${app.username}
spring.datasource.password=${app.password}
#datasource properties
spring.datasource.driver-class-name=${app.driver}
#hibernate properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
#hibernate dialect
spring.jpa.properties.hibernate.dialect=${app.dialect}
#cors properties
cors.allowed-origins=${cors.origin:*}

#Swagger properties
#http://10.11.201.120:8081/swagger-ui/index.html
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/v1/api-docs

#logging properties
logging.pattern.console=${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

