# Kafka Streams configuration
spring.application.name=SpringBootKafkaStreams
# Kafka bootstrap server
spring.kafka.bootstrap-servers=localhost:9092
# Default SerDes (String)
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
# Optional: Clean up on restart (development only)
spring.kafka.streams.cleanup.on-startup=true

