# Kafka bootstrap server
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Streams configuration
spring.kafka.streams.application-id=kafka-streams

# Default SerDes (String)
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
