app.name=SpringProductDesigner
app.port=8081
app.url=jdbc:oracle:thin:@10.11.201.120:1521/XEPDB1
app.username=employee_user
app.password=employee_user
app.driver=oracle.jdbc.OracleDriver
app.dialect=org.hibernate.dialect.OracleDialect
cors.origin=http://localhost:4200