spring.application.name=config-server
server.port=8888

# Git or local config repo (example: local file system)
spring.cloud.config.server.git.uri=file:///F:/Personal/EraProject/nano-banking-service/config-repo