spring.application.name=CustomerServiceRedis
spring.datasource.url=jdbc:h2:mem:customers
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.redis.host=localhost
spring.redis.port=6379

spring.cache.type=redis
