resilience4j:
  circuitbreaker:
    instances:
      externalServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        recordExceptions:
        -  java.lang.RuntimeException
management:
  endpoints:
    web:
      exposure:
        include: "*"
